title: Rouge Lab
description: "Chinesiologo - Coaching endurance (ciclismo e corsa) e forza"
baseurl: "/Portfolio"
url: ""

markdown: kramdown
permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
